"""
Pydantic response models for the Founder Business Intelligence Agent.
"""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ChatResponse(BaseModel):
    """Response returned by the /chat endpoint."""

    success: bool = True

    response: str = Field(
        ...,
        description="Natural language response generated by the AI agent.",
    )

    summary: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Analytics summary used to generate the response.",
    )

    session_id: Optional[str] = Field(
        default=None,
        description="Conversation session identifier.",
    )


class HealthResponse(BaseModel):
    """Response returned by the /health endpoint."""

    status: str
    service: str
    version: str


class ErrorResponse(BaseModel):
    """Standard error response."""

    success: bool = False

    error: str

    details: Optional[str] = None


class AnalyticsResponse(BaseModel):
    """Optional response model for analytics endpoints."""

    success: bool = True

    metrics: Dict[str, Any]

    generated_at: Optional[str] = None


class ConversationHistoryResponse(BaseModel):
    """Conversation history response."""

    success: bool = True

    session_id: str

    history: List[Dict[str, str]]